"""empty message

Revision ID: a755c76285aa
Revises: 
Create Date: 2020-06-21 12:33:03.239214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a755c76285aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_customer_id'), 'customer', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_customer_name'), 'customer', ['customer_name'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=True)
    op.create_index(op.f('ix_product_product_type'), 'product', ['product_type'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=64), nullable=False),
    sa.Column('month_end', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_balance'), 'account', ['balance'], unique=False)
    op.create_index(op.f('ix_account_flag'), 'account', ['flag'], unique=False)
    op.create_index(op.f('ix_account_month_end'), 'account', ['month_end'], unique=False)
    op.create_index(op.f('ix_account_number'), 'account', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_number'), table_name='account')
    op.drop_index(op.f('ix_account_month_end'), table_name='account')
    op.drop_index(op.f('ix_account_flag'), table_name='account')
    op.drop_index(op.f('ix_account_balance'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_product_product_type'), table_name='product')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_customer_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
