"""empty message

Revision ID: 903656f2091e
Revises: 
Create Date: 2020-06-26 14:31:12.539677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903656f2091e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('month_end', sa.DateTime(), nullable=True),
    sa.Column('flag', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_balance'), 'accounts', ['balance'], unique=False)
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=True)
    op.create_index(op.f('ix_accounts_customer_name'), 'accounts', ['customer_name'], unique=False)
    op.create_index(op.f('ix_accounts_flag'), 'accounts', ['flag'], unique=False)
    op.create_index(op.f('ix_accounts_month_end'), 'accounts', ['month_end'], unique=False)
    op.create_index(op.f('ix_accounts_product_name'), 'accounts', ['product_name'], unique=False)
    op.create_index(op.f('ix_accounts_product_type'), 'accounts', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_product_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_product_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_month_end'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_flag'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_balance'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
